AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Naming/FileName:
  Exclude:
    - 'lib/grape-cache.rb'
