AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe

Naming/FileName:
  Exclude:
    - 'lib/grape-cache.rb'

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true
